### PR TITLE
updates site generator to Docusaurus V2 and refresh its view

### PR DESCRIPTION
**Pull request by viglucci**
This change updates the documentation site generator to leverage Docusaurus V2, as an upgrade from the previously used Docusaurus V1. The commit deltas are going to be quite extensive given that the static site generation output is included in one of the later commits to support the GitHub pages deployment, so I might recommend it best to review the example deployment below as the primary means of review.

Changes/overview:

- Updates the site generator to [Docusaurus V2](https://v2.docusaurus.io/).
  - Why upgrade to V2: https://v2.docusaurus.io/docs/#a-better-docusaurus-is-coming-to-town 
- Updated content on homepage to assist with directing visitors to important documentation.
- Adds additional language examples to homepage under language tabs.
- Updates documentation markdown files to leverage cascading headers for autogenerated "table of contents". 
- Addresses #21
- Adds contributing.md

Deployed example for review here: https://viglucci.github.io/rsocket-website/

image

### CODE REVIEW

**Comment by OlegDokuka** [comment]
@viglucci looks very nice! Awesome job! Requested more folks to provides their feedback as well!

**Review by OlegDokuka — APPROVED** [review]

**Comment by OlegDokuka** [comment]
Also, can we put our rsocket [logo](https://github.com/rsocket/rsocket-artwork/tree/master/rsocket-horizontal-logo) instead of RSocket as a text

**Comment by whyoleg** [comment]
Looks really cool!
I'll be happy to add an example of kotlin implementation, when it will be merged!

minor remark: isn't footer logo is too big ? :)

**Review by whyoleg — APPROVED** [review]

**Review by simonbasle — CHANGES_REQUESTED** [review]
nice! I would rearrange the 3 section at the top of the homepage to point to `docs/motivations`, `/docs/protocol` and `/docs/implementations` respectively. maybe change the small paragraph or the button texts accordingly (eg. to refer to the direct links to implementations below in the 3rd block).

However, with that change there wouldn't be a direct link to the FAQ, maybe to add somewhere else?

**Comment by yschimke** [comment]
Looks great.  Some of the links are hard to detect because color matches the text

image

**Review by yschimke — APPROVED** [review]

**Comment by viglucci** [comment]
- Index header udpated to use logo image (https://github.com/rsocket/rsocket-website/pull/24#issuecomment-767449380)
- Footer logo size adjusted to reflect feedback (https://github.com/rsocket/rsocket-website/pull/24#issuecomment-767452641)
- Featured items adjusted to reflect feedback + primary CTA in header updated to reference FAQ (https://github.com/rsocket/rsocket-website/pull/24#pullrequestreview-576220913)
- Link CSS/styling updated to be more noticable (https://github.com/rsocket/rsocket-website/pull/24#issuecomment-767720993)

**Review by SerCeMan — APPROVED** [review]
Looks awesome!

I personally really like pink colours on https://viglucci.github.io/rsocket-website/, helps to keep it distinctive and stay on brand 🚀

**Review by jjeffcaii — APPROVED** [review]
Awesome job! 👍 💯 🥇

**Comment by simonbasle** [comment]
very nice update @viglucci!
I should ask, what is the source and license for the CTA images?

**Comment by yschimke** [comment]
This is super impactful, great to see someone focus on this!

**Comment by viglucci** [comment]
Thanks all for the kind words, and thanks to Oleg for adding me to the org to help manage the documentation.

@simonbasle to answer your question; the illustrations come from [Undraw](https://undraw.com), and have a [completely open source license](https://undraw.co/license).

**Pull request merged**
