### PR TITLE
adds rsocket-kotlin samples

### PR DESCRIPTION
**Pull request by whyoleg**
* update implementations with ktor for rsocket-kotlin
* turn on kotlin highlighting
* add kotlin sample to index.js

### CODE REVIEW

**Review by OlegDokuka — CHANGES_REQUESTED** [review]
@whyoleg can we add please some symmetric examples of client + server (without the usage of external services)

**Comment by whyoleg** [comment]
fixed.
BTW, how website is deployed?
is it automated?

**Comment by OlegDokuka** [comment]
@whyoleg yes

**Review by OlegDokuka — APPROVED** [review]
LGTM

**Pull request merged**
