### PR TITLE
docs: Guide Section with rsocket-js Guide

### PR DESCRIPTION
**Pull request by viglucci**
Adds a "Guides" section + a basic guide to `rsocket-js`.

This branch leverages the branch from #29 as a base, so some changes are general-purpose fixes/improvements that were made there.

### Motivation:

Inspired by https://github.com/rsocket/rsocket-js/issues/125.

This hopefully closes some of the gaps with how to actually get started building something with `rsocket-js`, and hopefully establishes a pattern for writing "guides" for the other language-specific implementations.

I was struggling a bit with #29 on how to broach the various subjects in a generic way without getting too specific to the various language implementations, and as such, I think a good and effective use of time in the meantime would be to create a few guides, rather than try and write an overly generic high-level document specific to a bunch of the different language implementations.

I'm not advocating that we abandon #29, but in the meantime, we can provide some value to consumers with this addition, and potentially some other guides.

### Modifications:

Documentation content additions.

### Result:

Guides menu items and content added for `rsocket-js`.

image

See preview on Netlify: https://deploy-preview-52--rsocket.netlify.app/guides

### CODE REVIEW

**Review by SerCeMan — COMMENTED** [review]
Nice! I wonder if we can provide some links to runnable example projects with rsocket-js. Even with examples, it might be hard to get some form of hello-world running.

**Comment by viglucci** [comment]
That was my thoughts exactly. The examples in [packages/rsocket-examples/](https://github.com/rsocket/rsocket-js/tree/master/packages/rsocket-examples/src) are great, but I personally like to be able to run examples and demos, which is why I also started hacking on some: https://github.com/viglucci/rsocket-js-examples.

I'm hoping to provide a few fully self-contained and runnable examples for different scenarios, likely leverages concepts from `rsocket-examples`. If I get a few done and we think they would be better lived in a different repo or org that would be fine as well, happy to move them.

**Comment by yschimke** [comment]
You could put an example with rsc or rsocket-cli

```
$ rsocket-cli ws://127.0.0.1:9898 --request --dataFormat=text/plain
Sun Apr 25 2021 21:56:42 GMT+0100 (British Summer Time)
```

**Comment by viglucci** [comment]
@SerCeMan @OlegDokuka @flyinprogrammer please let me know if you have any merge blocking feedback/requests and I can prioritize those items. If not, I'm hoping to get at least one approval before merging. Thanks!

**Review by OlegDokuka — APPROVED** [review]

**Pull request merged**
