### PR TITLE
feat: deploy via gh-pages branch

### PR DESCRIPTION
**Pull request by viglucci**
feat: leverage deployment via gh-pages branch to avoid cluttering source control with compiled output

### Motivation:

The scripts listed in `package.json` were a hodgepodge of scripts for docusaurus v1 and docusaurus v2. The scripts are now cleaned up to only reference actions that can actually be completed. Additionally, the CI script now references the build command rather than the deploy command, which better aligns with the result of running the script respectively.

Lastly, and likely more importantly, we will now leverage the `gh-pages` branch to house compiled and deploy output, which allows us to not pollute VCS history of working branches.

### Modifications:

- Remove defunct scripts from `package.json` that no longer worked
- Invoke `npm run build` in CI rather than `npm run deploy`.
- Move to deployment via gh-pages branch

### Result:

There should be no noticable change to end users or normal maintainer development flows.

### CODE REVIEW

**Review by flyinprogrammer — APPROVED** [review]
I would use this PR to switch over to gh-pages now so that we don't accidentally run npm deploy and create more madness

**Comment by viglucci** [comment]
Sounds good to me. I'll include that as well.

**Comment by viglucci** [comment]
I think we are pretty close to having the deployment working via the `gh-pages` branch, but I'm hitting an issue with the git commits invoked via `npm run deploy` failing due to permissions. I think we'll need a deployment key setup as [suggested in the guide](https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions), unless @flyinprogrammer you have thoughts on getting that to work without using SSH?

**Comment by flyinprogrammer** [comment]
@viglucci sorry for the radio silence i'll look into this very shortly

**Pull request merged**
