### PR TITLE
Fixed a sentence that was not clear

### PR DESCRIPTION
**Pull request by MrMoon**
> This protocol is designed for use both in datacenter, server-to-server use cases, as well as server-to-device use cases over the internet, such as to mobile devices or browsers.

was not very clear on the `for use both in`

### CODE REVIEW

**Review by OlegDokuka — CHANGES_REQUESTED** [review]
I suggest changing it first at protocol repo (https://github.com/rsocket/rsocket) and then porting it to the webpage

**Comment by MrMoon** [comment]
@OlegDokuka Done 👍🏽

**Comment by flyinprogrammer** [comment]
@MrMoon sorry my changes broke this PR, you'll find this file here now: https://github.com/rsocket/rsocket-website/blob/master/content-docs/motivations.md

Also, we dropped gradle, so now it's just an nodejs/npm workflow. I'm about to go document the "new" PR process in https://github.com/rsocket/rsocket-website/blob/master/CONTRIBUTING.md  I'm hoping this PR and currently workflow won't be particularly impacted. If it is, do speak up!

My apologies for any frustration this might have caused, we really appreciate your feedback and contributions!

**Comment by MrMoon** [comment]
no worries, I will make sure to follow the new PR process 👍🏽

**Comment by MrMoon** [comment]
I will close this since it only belongs in the rsocket protocol repo

**Pull request closed without merging**
